import subprocess
subprocess.call("sudo apt install git" shell=True)
subprocess.call("sudo apt install php" shell=True)
subprocess.call("git clone https://github.com/xHak9x/SocialPhish.git" shell=True)
subprocess.call("git clone https://github.com/tiptoettt/instashell.git" shell=True)
subprocess.call("git clone https://github.com/IAmBlackHacker/Facebook-BruteForce.git" shell=True)
subprocess.call("git clone https://github.com/GiacomoLaw/Keylogger.git" shell=True)
subprocess.call("git clone https://github.com/noob-hackers/grabcam.git" shell=True)
subprocess.call("https://github.com/greyli/sayhello.git" shell=True)
subprocess.call("https://github.com/dadi32/PhoneSploit.git" shell=True)
subprocess.call("https://github.com/epsylon/ufonet.git" shell=True)
subprocess.call("https://github.com/NewEraCracker/LOIC.git" shell=True)
